name: morphicsentient
favicon: null
layout_spectrum: 0.5543530930299312
typography_spectrum: 0.8252670059446245
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.06381153431721032
  lightness: 0.9926336880307645
  saturation: 0.3458567764610052
  rhythmicContrast: 0.09822013694792986
purpose: []
